import pytest


def pytest_collection_modifyitems(config, items):
    """Skip auto-generated placeholder tests that still contain assert False.

    Heuristic: any test function literally named ``test_placeholder`` is
    considered an unfinished skeleton generated by
    ``src.test_skeleton_generator`` and should be skipped to prevent CI noise.
    """
    for item in items:
        if item.name == "test_placeholder":
            item.add_marker(pytest.mark.skip(reason="Auto-generated test stub")) 