"""developer_needs.py – Step 4.2 Analyze Real-World Context & Developer Needs 📊⚡️

This module **bridges a gap** between low-level KPI logs (see
:pymod:`src.success_metrics`) and *actionable insights* required by engineering
leads or prompt-building assistants.

It implements the theoretical **4.2 Analyze Real-World Context and Developer
Needs** section:

* **Lower environmental footprint** – surfaces *energy-intensive* LLM usage and
  suggests local-first optimisations when the *remote-execution ratio* exceeds
  a threshold.
* **Transparent usage & energy feedback** – aggregates ecological impact in an
  easily digestible summary that can be embedded into dashboards, README badges
  or LLM prompts.
* **Developer agency in AI suggestions** – derives an *override-rate* metric to
  quantify how often humans overrule AI code changes thereby highlighting
  potential trust or UX shortcomings.

The analyser purposefully re-uses *existing* JSON-Lines logs to avoid additional
instrumentation overhead.  No personal data is processed; all heuristics are
fully transparent and local-first.

Security/Ethical Notes
~~~~~~~~~~~~~~~~~~~~~
* Runs **locally** – never contacts remote endpoints.
* Reads only the metrics file path given (defaults to `.success_metrics.jsonl`).
* Uses simple, explainable thresholds so teams can tweak them according to
  their sustainability or UX policies.

Example CLI usage
-----------------
```bash
python -m src.developer_needs report --pretty
```
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

import typer

from .logger import get_logger, setup_logging
from .success_metrics import MetricsStore, _DEFAULT_STORE_PATH  # type: ignore – private constant ok for default

__all__ = [
    "analyze_developer_needs",
    "Need",
    "app",
]

_log = get_logger(__name__)

# ---------------------------------------------------------------------------
# Heuristics & thresholds (tweakable)
# ---------------------------------------------------------------------------

_DEFAULT_ENERGY_THRESHOLD_KWH = 0.1  # highlight when total energy exceeds this per day
_DEFAULT_LOCAL_EXEC_RATIO = 75.0  # % local execution considered acceptable
_DEFAULT_OVERRIDE_TARGET = 20.0  # % overrides expected for healthy HITL


class Need(str):
    """High-level need identifiers returned in the *needs* section."""

    ENVIRONMENTAL_FOOTPRINT = "lower_environmental_footprint"
    TRANSPARENCY = "transparent_usage_and_energy_feedback"
    AGENCY = "developer_agency"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def analyze_developer_needs(
    metrics_path: str | Path = _DEFAULT_STORE_PATH,
    *,
    energy_threshold_kwh: float = _DEFAULT_ENERGY_THRESHOLD_KWH,
    local_exec_target_pct: float = _DEFAULT_LOCAL_EXEC_RATIO,
    override_target_pct: float = _DEFAULT_OVERRIDE_TARGET,
) -> Dict[str, Any]:
    """Return **insights** derived from success-metrics *metrics_path*.

    Parameters
    ----------
    metrics_path:
        JSON-Lines file generated by :pymod:`src.success_metrics`.  Defaults to
        the same file used by that module.
    energy_threshold_kwh:
        Total daily energy consumption (kWh) above which the report will flag
        high footprint usage.
    local_exec_target_pct:
        Minimum percentage of *local* executions expected – lower values
        trigger optimisation suggestions.
    override_target_pct:
        Desired developer override rate (HITL).  Values **below** this target
        indicate insufficient agency.

    Returns
    -------
    Dict[str, Any]
        Machine-readable structure containing *metrics* and *recommendations*.
    """

    store = MetricsStore(metrics_path)
    agg = store.aggregate()

    _log.debug("Aggregated metrics: %s", agg)

    # -----------------------------
    # Extract metrics we care about
    # -----------------------------

    energy_data = agg.get("energy_footprint", {})
    override_data = agg.get("override_activity", {})

    # Safety fallbacks when keys missing
    total_kwh = float(energy_data.get("total_kwh", 0.0))
    local_ratio = float(energy_data.get("local_execution_ratio", 0.0))
    override_rate = float(override_data.get("override_rate_pct", 0.0))

    needs: Dict[str, Dict[str, Any]] = {
        Need.ENVIRONMENTAL_FOOTPRINT: {
            "total_kwh": total_kwh,
            "threshold_kwh": energy_threshold_kwh,
            "status": "high" if total_kwh > energy_threshold_kwh else "ok",
        },
        Need.TRANSPARENCY: {
            "local_execution_ratio_pct": local_ratio,
            "target_pct": local_exec_target_pct,
            "status": "low_local_exec" if local_ratio < local_exec_target_pct else "ok",
        },
        Need.AGENCY: {
            "override_rate_pct": override_rate,
            "target_pct": override_target_pct,
            "status": "low_agency" if override_rate < override_target_pct else "ok",
        },
    }

    # ---------------------------------
    # Build human-readable recommendations
    # ---------------------------------

    recommendations: List[str] = []

    if needs[Need.ENVIRONMENTAL_FOOTPRINT]["status"] == "high":
        recommendations.append(
            "Energy consumption exceeds the daily threshold – consider enforcing local-first LLM execution (FORCE_LOCAL_LLM=1) or model quantisation."
        )

    if needs[Need.TRANSPARENCY]["status"] == "low_local_exec":
        recommendations.append(
            "Less than {:.0f}% operations were local. Provide clear energy feedback in the UI and offer on-device inference options.".format(
                local_exec_target_pct
            )
        )

    if needs[Need.AGENCY]["status"] == "low_agency":
        recommendations.append(
            "Developer override rate is below the desired {:.0f}% – improve suggestion preview UX or require explicit approval before applying AI changes.".format(
                override_target_pct
            )
        )

    result: Dict[str, Any] = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "metrics_file": str(Path(metrics_path).resolve()),
        "needs": needs,
        "recommendations": recommendations,
    }

    _log.debug("Developer needs analysis result: %s", result)
    return result


# ---------------------------------------------------------------------------
# Typer CLI – quick standalone usage
# ---------------------------------------------------------------------------

app = typer.Typer(
    add_completion=False,
    help="4.2 Developer Needs analyser – aggregates success metrics for actionable insights.",
)


@app.command()
def report(
    metrics_file: Path = typer.Option(
        _DEFAULT_STORE_PATH, "--metrics", help="Path to .success_metrics.jsonl file"
    ),
    pretty: bool = typer.Option(False, "--pretty", help="Pretty human-readable output"),
    json_output: bool = typer.Option(False, "--json", help="Machine-readable JSON output"),
    verbose: bool = typer.Option(False, "--verbose", "-v"),
):
    """Generate a developer-needs **report** from *metrics_file*."""

    setup_logging("DEBUG" if verbose else "INFO")
    data = analyze_developer_needs(metrics_file)

    if json_output:
        typer.echo(json.dumps(data, indent=2))
        raise typer.Exit()

    if pretty:
        _pretty_print(data)
    else:
        typer.echo(json.dumps(data, indent=2))


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _pretty_print(data: Dict[str, Any]) -> None:  # noqa: D401 – imperative mood not needed
    """Human-friendly printer for :pyfunc:`report`."""

    typer.secho("\n🔍 Developer Needs Assessment", bold=True)
    typer.echo(f"Metrics file : {data['metrics_file']}")
    typer.echo(f"Timestamp     : {data['timestamp']}")

    for need_key, details in data["needs"].items():
        title = need_key.replace("_", " ").title()
        status = details["status"].upper()
        colour = {
            "ok": "green",
            "high": "red",
            "low_local_exec": "yellow",
            "low_agency": "yellow",
        }.get(status.lower(), "white")
        typer.secho(f"\n{title} – [{status}]", fg=colour, bold=True)
        for k, v in details.items():
            if k == "status":
                continue
            typer.echo(f"  {k}: {v}")

    if data["recommendations"]:
        typer.secho("\nRecommended actions:", bold=True)
        for rec in data["recommendations"]:
            typer.echo(f"  • {rec}")
    else:
        typer.secho("\n✅ All metrics within acceptable thresholds.", fg="green")


# ---------------------------------------------------------------------------
# Self-test (manual) – ``python -m src.developer_needs report --pretty``
# ---------------------------------------------------------------------------

if __name__ == "__main__":  # pragma: no cover
    app()